// Generated by gencpp from file edge_info/vhc_cmd.msg
// DO NOT EDIT!


#ifndef EDGE_INFO_MESSAGE_VHC_CMD_H
#define EDGE_INFO_MESSAGE_VHC_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edge_info
{
template <class ContainerAllocator>
struct vhc_cmd_
{
  typedef vhc_cmd_<ContainerAllocator> Type;

  vhc_cmd_()
    : vhcid(0)
    , cmd(0)  {
    }
  vhc_cmd_(const ContainerAllocator& _alloc)
    : vhcid(0)
    , cmd(0)  {
  (void)_alloc;
    }



   typedef uint32_t _vhcid_type;
  _vhcid_type vhcid;

   typedef uint32_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::edge_info::vhc_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edge_info::vhc_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct vhc_cmd_

typedef ::edge_info::vhc_cmd_<std::allocator<void> > vhc_cmd;

typedef boost::shared_ptr< ::edge_info::vhc_cmd > vhc_cmdPtr;
typedef boost::shared_ptr< ::edge_info::vhc_cmd const> vhc_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edge_info::vhc_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edge_info::vhc_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace edge_info

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'edge_info': ['/home/yulans/Documents/edge/cnedge/Dependable-Edge-computing/rosws/src/edge_info/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::edge_info::vhc_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edge_info::vhc_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edge_info::vhc_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edge_info::vhc_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edge_info::vhc_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edge_info::vhc_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edge_info::vhc_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "431b3cb4cfa302ca931f4d197d26c3a0";
  }

  static const char* value(const ::edge_info::vhc_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x431b3cb4cfa302caULL;
  static const uint64_t static_value2 = 0x931f4d197d26c3a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::edge_info::vhc_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edge_info/vhc_cmd";
  }

  static const char* value(const ::edge_info::vhc_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edge_info::vhc_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 vhcid\n\
uint32 cmd\n\
";
  }

  static const char* value(const ::edge_info::vhc_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edge_info::vhc_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vhcid);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vhc_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edge_info::vhc_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edge_info::vhc_cmd_<ContainerAllocator>& v)
  {
    s << indent << "vhcid: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.vhcid);
    s << indent << "cmd: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDGE_INFO_MESSAGE_VHC_CMD_H
